GET http://127.0.0.1:3000/users

###

GET http://127.0.0.1:3000/users/:id

###

POST http://127.0.0.1:3000/users
Content-Type: application/json  

{
    "username": "TheBeanKing",
    "password": "456"
}

###

DELETE http://127.0.0.1:3000/users/63db15500b51343905f4f28c