GET http://127.0.0.1:3000/users

###

GET http://127.0.0.1:3000/users/:id

###

POST http://127.0.0.1:3000/users
Content-Type: application/json  

{
    "username": "hello_world",
    "password": "12345678"
}

###

DELETE http://127.0.0.1:3000/users/